# Generated by Django 4.2.17 on 2024-12-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentalSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Serie Documental',
                'verbose_name_plural': 'Series Documentales',
            },
        ),
        migrations.CreateModel(
            name='DocumentalSubserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Subserie Documental',
                'verbose_name_plural': 'Subseries Documentales',
            },
        ),
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Grado de Educación')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Siglas')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Agregado')),
                ('education_degree', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managers', to='app.educationdegree', verbose_name='Educación')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Población')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='app.manager', verbose_name='Encargado')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='app.municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subsections', to='app.manager', verbose_name='Responsable')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subsections', to='app.section', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Subsección',
                'verbose_name_plural': 'Subsecciones',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('file_number', models.IntegerField(verbose_name='Número de Expediente')),
                ('initial_date', models.DateField(verbose_name='Fecha Inicio')),
                ('final_date', models.DateField(verbose_name='Fecha Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boxes', to='app.section', verbose_name='Sección')),
                ('serie', models.ManyToManyField(related_name='boxes', to='app.documentalserie', verbose_name='Serie Documental')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boxes', to='app.subsection', verbose_name='Subsección')),
                ('subserie', models.ManyToManyField(related_name='boxes', to='app.documentalsubserie', verbose_name='Subserie Documental')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
