# Generated by Django 4.2.17 on 2025-02-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_documentalserie_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.box', verbose_name='Caja')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.filetype', verbose_name='Tipo archivo')),
            ],
        ),
    ]
