# Generated by Django 4.2.17 on 2025-02-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_filetype_docfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docfile',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': 'Tipo archivos', 'verbose_name_plural': 'Tipos archivos'},
        ),
        migrations.AddField(
            model_name='docfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-02 00:00:00', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
