# Generated by Django 4.2.17 on 2024-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='population',
        ),
        migrations.AddField(
            model_name='municipality',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
    ]
