# Generated by Django 4.2.17 on 2025-03-19 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_docfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfile',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de elaboración'),
        ),
        migrations.AlterField(
            model_name='docfile',
            name='description',
            field=models.TextField(default='No hay descripción', verbose_name='Descripción'),
        ),
    ]
